//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvMakerWebsiteApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQualification
    {
        public int QualificationsId { get; set; }
        public int CvId { get; set; }
        public string Qualifications { get; set; }
    
        public virtual tblUserCvDetail tblUserCvDetail { get; set; }
    }
}
