//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvMakerWebsiteApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReferencesDetail
    {
        public int ReferencesId { get; set; }
        public int Cvid { get; set; }
        public string ReferencesDetails { get; set; }
    
        public virtual tblUserCvDetail tblUserCvDetail { get; set; }
    }
}
