//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvMakerWebsiteApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserPersonalDetail
    {
        public int PersonalId { get; set; }
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string DateOfBirth { get; set; }
        public string UserPhoto { get; set; }
        public string MobileNo { get; set; }
        public string Address { get; set; }
    
        public virtual tblUserAccountDetail tblUserAccountDetail { get; set; }
    }
}
