//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventReminderService.Areas.Admin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EventReminderEntities1 : DbContext
    {
        public EventReminderEntities1()
            : base("name=EventReminderEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAdminAccount> tblAdminAccounts { get; set; }
        public virtual DbSet<tblCity> tblCities { get; set; }
        public virtual DbSet<tblCountry> tblCountrys { get; set; }
        public virtual DbSet<tblState> tblStates { get; set; }
        public virtual DbSet<tblHintQuestion> tblHintQuestions { get; set; }
        public virtual DbSet<tblRelationship> tblRelationships { get; set; }
        public virtual DbSet<tblReligion> tblReligions { get; set; }
    
        public virtual ObjectResult<tblAdminAccount> SP_CheckAdminLogin(string userName, string password)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tblAdminAccount>("SP_CheckAdminLogin", userNameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<tblAdminAccount> SP_CheckAdminLogin(string userName, string password, MergeOption mergeOption)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tblAdminAccount>("SP_CheckAdminLogin", mergeOption, userNameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_CheckAdminOldPassword(string userName, string oldPassword)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var oldPasswordParameter = oldPassword != null ?
                new ObjectParameter("OldPassword", oldPassword) :
                new ObjectParameter("OldPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_CheckAdminOldPassword", userNameParameter, oldPasswordParameter);
        }
    }
}
