//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventReminderService.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReligion
    {
        public int ReligionId { get; set; }
        public string ReligionName { get; set; }
        public bool IsActive { get; set; }
    }
}
