<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="StudentsDetailsTable.aspx.cs" Inherits="MyFirstProject.StudentsDetailsTable" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" EnableTheming="True">
                <Columns>
                    <asp:BoundField HeaderText="الإسم" DataField="name" />
                    <asp:BoundField HeaderText="العنوان" DataField="address1" />
                    <asp:BoundField HeaderText="اسم الأستاذ (الحلقة)" DataField="teacherName" />
                    <asp:BoundField HeaderText="رقم الهاتف" DataField="phoneNumber" />
                    <asp:BoundField HeaderText="رقم هاتف الأهل" DataField="familyNumber" />
                </Columns>
            </asp:GridView>
        </div>
    </form>
</body>
</html>
