//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventReminderService.Areas.User.Models
{
    using System;
    
    public partial class BindRelationship
    {
        public int RelationshipId { get; set; }
        public string RelationshipName { get; set; }
        public bool IsActive { get; set; }
    }
}
