//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventReminderService.Areas.User.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EventReminderEntities5 : DbContext
    {
        public EventReminderEntities5()
            : base("name=EventReminderEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblBirthdayDetail> tblBirthdayDetails { get; set; }
        public virtual DbSet<tblBirthdayReminder> tblBirthdayReminders { get; set; }
        public virtual DbSet<tblRelationshipUser> tblRelationshipUsers { get; set; }
    
        public virtual ObjectResult<BindCity> SP_BindCity(Nullable<int> stateId)
        {
            var stateIdParameter = stateId.HasValue ?
                new ObjectParameter("StateId", stateId) :
                new ObjectParameter("StateId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BindCity>("SP_BindCity", stateIdParameter);
        }
    
        public virtual ObjectResult<BindCountry> SP_BindCountry()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BindCountry>("SP_BindCountry");
        }
    
        public virtual ObjectResult<BindHintQuestion> SP_BindHintQuestion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BindHintQuestion>("SP_BindHintQuestion");
        }
    
        public virtual ObjectResult<BindState> SP_BindState(Nullable<int> countryId)
        {
            var countryIdParameter = countryId.HasValue ?
                new ObjectParameter("CountryId", countryId) :
                new ObjectParameter("CountryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BindState>("SP_BindState", countryIdParameter);
        }
    
        public virtual ObjectResult<UserDetails> SP_GetUserDetails(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UserDetails>("SP_GetUserDetails", userIdParameter);
        }
    
        public virtual int SP_UpdateUserProfile(Nullable<int> userId, string newPassword, Nullable<int> hintQuestionId, string newHintQuestion, string hintQuestionAnswer, string firstName, string middleName, string lastName, string nickeName, string dateOfBirth, string anniversaryDate, string gender, Nullable<bool> isAgeSecret, string mobileNo, string userPhoto, string addressLine1, Nullable<int> countryId, Nullable<int> stateId, Nullable<int> cityId, string pinCode)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var newPasswordParameter = newPassword != null ?
                new ObjectParameter("NewPassword", newPassword) :
                new ObjectParameter("NewPassword", typeof(string));
    
            var hintQuestionIdParameter = hintQuestionId.HasValue ?
                new ObjectParameter("HintQuestionId", hintQuestionId) :
                new ObjectParameter("HintQuestionId", typeof(int));
    
            var newHintQuestionParameter = newHintQuestion != null ?
                new ObjectParameter("NewHintQuestion", newHintQuestion) :
                new ObjectParameter("NewHintQuestion", typeof(string));
    
            var hintQuestionAnswerParameter = hintQuestionAnswer != null ?
                new ObjectParameter("HintQuestionAnswer", hintQuestionAnswer) :
                new ObjectParameter("HintQuestionAnswer", typeof(string));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var middleNameParameter = middleName != null ?
                new ObjectParameter("MiddleName", middleName) :
                new ObjectParameter("MiddleName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var nickeNameParameter = nickeName != null ?
                new ObjectParameter("NickeName", nickeName) :
                new ObjectParameter("NickeName", typeof(string));
    
            var dateOfBirthParameter = dateOfBirth != null ?
                new ObjectParameter("DateOfBirth", dateOfBirth) :
                new ObjectParameter("DateOfBirth", typeof(string));
    
            var anniversaryDateParameter = anniversaryDate != null ?
                new ObjectParameter("AnniversaryDate", anniversaryDate) :
                new ObjectParameter("AnniversaryDate", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            var isAgeSecretParameter = isAgeSecret.HasValue ?
                new ObjectParameter("IsAgeSecret", isAgeSecret) :
                new ObjectParameter("IsAgeSecret", typeof(bool));
    
            var mobileNoParameter = mobileNo != null ?
                new ObjectParameter("MobileNo", mobileNo) :
                new ObjectParameter("MobileNo", typeof(string));
    
            var userPhotoParameter = userPhoto != null ?
                new ObjectParameter("UserPhoto", userPhoto) :
                new ObjectParameter("UserPhoto", typeof(string));
    
            var addressLine1Parameter = addressLine1 != null ?
                new ObjectParameter("AddressLine1", addressLine1) :
                new ObjectParameter("AddressLine1", typeof(string));
    
            var countryIdParameter = countryId.HasValue ?
                new ObjectParameter("CountryId", countryId) :
                new ObjectParameter("CountryId", typeof(int));
    
            var stateIdParameter = stateId.HasValue ?
                new ObjectParameter("StateId", stateId) :
                new ObjectParameter("StateId", typeof(int));
    
            var cityIdParameter = cityId.HasValue ?
                new ObjectParameter("CityId", cityId) :
                new ObjectParameter("CityId", typeof(int));
    
            var pinCodeParameter = pinCode != null ?
                new ObjectParameter("PinCode", pinCode) :
                new ObjectParameter("PinCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UpdateUserProfile", userIdParameter, newPasswordParameter, hintQuestionIdParameter, newHintQuestionParameter, hintQuestionAnswerParameter, firstNameParameter, middleNameParameter, lastNameParameter, nickeNameParameter, dateOfBirthParameter, anniversaryDateParameter, genderParameter, isAgeSecretParameter, mobileNoParameter, userPhotoParameter, addressLine1Parameter, countryIdParameter, stateIdParameter, cityIdParameter, pinCodeParameter);
        }
    
        public virtual ObjectResult<GetBirthdayDetailsByUserId> SP_GetBirthdayDetailsByUserId(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBirthdayDetailsByUserId>("SP_GetBirthdayDetailsByUserId", userIdParameter);
        }
    
        public virtual ObjectResult<BindRelationship> SP_BindRelationship()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BindRelationship>("SP_BindRelationship");
        }
    
        public virtual ObjectResult<GetBirthdayDetailsById> SP_GetBirthdayDetailsById(Nullable<int> birthdayDetailsId)
        {
            var birthdayDetailsIdParameter = birthdayDetailsId.HasValue ?
                new ObjectParameter("BirthdayDetailsId", birthdayDetailsId) :
                new ObjectParameter("BirthdayDetailsId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBirthdayDetailsById>("SP_GetBirthdayDetailsById", birthdayDetailsIdParameter);
        }
    
        public virtual ObjectResult<GetBirthdayReminder> SP_GetBirthdayReminder(Nullable<int> birthdayDetailsId, Nullable<int> userId)
        {
            var birthdayDetailsIdParameter = birthdayDetailsId.HasValue ?
                new ObjectParameter("BirthdayDetailsId", birthdayDetailsId) :
                new ObjectParameter("BirthdayDetailsId", typeof(int));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBirthdayReminder>("SP_GetBirthdayReminder", birthdayDetailsIdParameter, userIdParameter);
        }
    }
}
