//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventReminderService.Areas.User.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBirthdayReminder
    {
        public int BirthdayReminderId { get; set; }
        public int UserId { get; set; }
        public int BirthdayDetailsId { get; set; }
        public Nullable<bool> C30DaysBefore { get; set; }
        public Nullable<bool> C14DaysBefore { get; set; }
        public Nullable<bool> C7DaysBefore { get; set; }
        public Nullable<bool> C3DaysBefore { get; set; }
        public Nullable<bool> DayOfEvent { get; set; }
    
        public virtual tblBirthdayDetail tblBirthdayDetail { get; set; }
    }
}
