//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventReminderService.Areas.User.Models
{
    using System;
    
    public partial class UserDetails
    {
        public int UserId { get; set; }
        public string EmailId { get; set; }
        public Nullable<int> HintQuestionId { get; set; }
        public string NewHintQuestion { get; set; }
        public string HintQuestionAnswer { get; set; }
        public Nullable<System.DateTime> DateOfRegistration { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string NickName { get; set; }
        public string Gender { get; set; }
        public string DateOfBirth { get; set; }
        public string AnniversaryDate { get; set; }
        public Nullable<bool> IsAgeSecert { get; set; }
        public string UserPhoto { get; set; }
        public string MobileNo { get; set; }
        public string AddressLine1 { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string PinCode { get; set; }
    }
}
